### ISSUE TITLE
La craftchest

### ISSUE THREAD

**Issue by katyamo** [LIUKRAST/HemeraldTexturePackCommunity#13]
La craftchest(da craftingtable + chest) è una chest che da non accovacciato è una cassa ma se tu abbassi lo usi come craftingtable
By ale_derby(sono in un altro account)

**Comment by LIUKRAST** [comment]
L'idea è carina ma non conforme allo stile generale della mod. Sarebbe un'aggiunta che ridurrebbe solo gli slot nell'inventario e lo spazio nel proprio mondo. Personalmente non è male, ma preferirei aggiungere cose nuove nella mod piuttosto che roba già esistente. Grazie comunque per la proposta!
